//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "balance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::balance_member::Entity")]
    BalanceMember,
}

impl Related<super::balance_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BalanceMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
