//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_debt")]
pub struct Model {
    pub creditor_id: String,
    pub debtor_id: String,
    pub amount: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::balance_member::Entity",
        from = "Column::DebtorId",
        to = "super::balance_member::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BalanceMember2,
    #[sea_orm(
        belongs_to = "super::balance_member::Entity",
        from = "Column::CreditorId",
        to = "super::balance_member::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BalanceMember1,
}

impl ActiveModelBehavior for ActiveModel {}
